### ISSUE TITLE
+ for new units is not very "Android"

### ISSUE THREAD

**Issue by lxalln** [allendevco/pill-logger#23]
It would probably be better to have it say "Add new..."

Although I think ideally a dialog, in a dialog, in a dialog is probably not our best solution in the long term. But for now, it'll do.

**Comment by Dreagen** [comment]
I initially did this as Add new... but it didn't look right to me. I'll put it back and see what you think

**Comment by lxalln** [comment]
Maybe have a divider above it and try making "Add new..." italic? Something to make it stand out?

**Comment by Dreagen** [comment]
Yeah that might be worth a go

**Comment by Dreagen** [comment]
Maybe even the italics would be enough, I don't think the divider would look very good, but I will play with it at lunch
