### ISSUE TITLE
Allow adding to units drop down

### ISSUE THREAD

**Issue by lxalln** [allendevco/pill-logger#7]
This will allow users to create their own 'units'.

[Enchant request](https://pilllogger.enchant.com/spa/ticket/565f892469702d78d40001ee)
>I just wanted to request that for dosage to add a "custom" option so we can add dosages for non-oral meds, for example, drops, sprays, inches/cm, or patches for eye drops, nasal sprays, and topical meds. This would be very helpful!

**Comment by lxalln** [comment]
I'm not sure how best to achieve this. Maybe just present with a custom option and allow the to create them on the fly?

Needs some thought.

**Comment by Dreagen** [comment]
Yeah I'm not sure either. Probably a custom option at the bottom of the drop down which brings up a dialog to add a new type?

**Comment by lxalln** [comment]
I guess we should have a way to remove them too? Some form of management screen?

- mg (5 medicines)
- ml (0 medicines) X REMOVE
- drops (3 medicines)
- sprays (1 medicine)

Something like that?

**Comment by Dreagen** [comment]
yeah actually that seems smart. Probably have an activity for it

**Comment by lxalln** [comment]
That you can get to from settings? Or straight from the left hand menu?

**Comment by Dreagen** [comment]
Tough call. I think it would be nice to have a like a settings cog on the drop down for it. Keep the settings close to where they are.

**Comment by lxalln** [comment]
Yeah, just to the right of the dropdown. I like it!

**Comment by Dreagen** [comment]
cool. Sounds like a plan!
